fiatconnect/specification

fiatconnect-api.md
swagger.yaml

Adding Brazilian currency Types [[reference](https://medium.com/celoorg/celo-launches-the-creal-stablecoin-11da0d560c1c)]

Add FiatType brazilian Real and cReal CryptoType

---

swagger.yaml

Updates to keep openapi spec in sync with markdown spec from changes in https://github.com/fiatconnect/specification/pull/19
added quoteId to quote response schema, and made guaranteedUntil required
added quoteId to transfer request body
added InvalidQuote error type

fix: quote ids swagger

---

fiatconnect-api.md

Small PR to add a simple `/clock` endpoint dedicated to synchronizing client-server clocks. This PR also updates all values representing dates to use the ISO 8601 standard rather than UNIX time, for the sake of consistency.
Will update the TOC and section numbering once the PR looks good to folks.

Add `/clock` endpoint for time synchronization

---

swagger.yaml

Includes updates from the following spec changes:
- add cREAL currency [fiatconnect/specification#23](https://github.com/fiatconnect/specification/pull/23)
- add AccountNumber fiat account type [fiatconnect/specification#16](https://github.com/fiatconnect/specification/pull/16)
- add InvalidParameters error [fiatconnect/specification#14](https://github.com/fiatconnect/specification/pull/14)
- add PersonalDataAndDocuments kyc type [fiatconnect/specification#6](https://github.com/fiatconnect/specification/pull/6)

fix: update openapi to be in sync with markdown spec

---

fiatconnect-api.md
swagger.yaml

Resolves #25 
Ensure that all `accounts` endpoints are plural, following google's api guide: https://cloud.google.com/apis/design/resource_names

fix: pluralize `accounts` endpoint

---

fiatconnect-api.md

This PR drops support for the JWT auth scheme in favor of using the Sign-In With Ethereum standard.

Rework Authentication scheme, require SIWE, remove JWT

---

fiatconnect-api.md
swagger.yaml

This PR updates the response from the `GET /transfer/:transferId` to include both the `transferId` and `transferAddress` fields. It also finally adds webhook payload schemas into the specification (which were in the types repo, but not here, for some reason...). 
These changes are somewhat related, in that the transfer status webhook payload should maintain parity with the the `GET /transfer/:transferId` response body, which was previously missing critical information that should have been included in the webhook payload (`transferId` and `transferAddress`, as mentioned above). Including `transferAddress` in the regular `GET /transfer/:transferId` response is useful independently as well, since previously, this information was _only available_ in the initial transfer request response, and …

Update `GET transfer/:transferId` response, add proper webhook payload schemas

---

fiatconnect-api.md

Removing some unused error codes as pointed out by @satish-ravi in [this PR](https://github.com/fiatconnect/specification/pull/17).

Remove some unused auth errors

---

fiatconnect-api.md

Adding this error helps clients understand when a transfer is rejected due to the provided fiat account actually being incompatible with the quote used for the transfers.

Add InvalidFiatAccount error

---

swagger.yaml

Looks like the new SIWE auth scheme and the clock endpoint are missing from the openapi spec. This adds them

fix: auth, clock openapi

---

fiatconnect-api.md

Since the amount to transfer is already encoded in the `quoteId` used for the transfer, it doesn't make sense to include a duplicate field for `amount` when initiating transfers. Same goes for `cryptoType` and `fiatType`.

Remove redundant information from transfer requests.

---

fiatconnect-api.md

Previously, the progression of transfer states was underspecified, as was the exact process for completing a transfer out, since transfers out require interaction from the end-user in order to complete. This PR adds in several, more descriptive transfer states, and specifies formal state machines for both transfers in and out.
I recommend checking the PR out in `View File` mode so you can see the rendered `mermaid` state machines.

Formalize transfer state machines

---

swagger.yaml

The schema is the "body" should be specified as a single parameter (not
multiple parameters):
https://swagger.io/docs/specification/2-0/describing-request-body/

Fix the OpenAPI 2.0 spec for the /auth/login endpoint

---

.github/workflows/validate-swagger.yml

`error Command "swagger-cli" not found.` in another PR: https://github.com/fiatconnect/specification/runs/6498938289?check_suite_focus=true

chore(ci): fix validate swagger workflow

---

fiatconnect-api.md

Hey @jophish and @jh2oman, as stated in one of our previous meeting, I created a branch to implement the `BankAccount` schema based on the IBAN. 
As, I know it is one of the most use bank account number ID, my thoughts were to use it as property for CI/CO providers that provided bank services.

Added BankAccount schema

---

fiatconnect-api.md

The SIWE docs make it more clear that the nonce should be *at least* 8 characters. This led to a misunderstanding with at least one provider API so far. https://docs.login.xyz/general-information/siwe-overview/eip-4361#message-field-descriptions

fix: clarify nonce should be at least 8 characters

---

fiatconnect-api.md
swagger.yaml

BREAKING CHANGE: changes http verb for quote endpoints, moves parameters from query to request body
requested by El Dorado, agreed to by Valora, Bitssa and PayChant

refactor!(quote): switch from GET /quote to POST /quote

---

fiatconnect-api.md

5.1.2 and 5.1.3, web hook description refers to the wrong endpoint
GET /accounts/:transferId  -->  GET /transfer/:transferId/status

docs: change Webhook Schema description typo

---

fiatconnect-api.md
swagger.yaml

It should be evident just by looking at a response object for a quote whether that quote is for a transfer out or a transfer in

feat(quotes): add tranferType field to successful quote responses

---

swagger.yaml

Previously, fields weren't required, which was causing our validation tool to silently pass partner checks when they should really have been failing.

fix(swagger): Make fields required in response bodies

---

fiatconnect-api.md

We've gotten feedback from providers that it may be helpful to be able to distinguish between quotes whose intent are to simply get a preview, vs. actually performing a transfer. The pain here is that currently, it's impossible to determine if a quote has a high likelihood of being executed, which means that certain provider implementations that rely on "locking up" liquidity for the duration of a quote's life may needlessly lock up large amounts of their liquidity for clients with no intention of actually using their services.
This PR adds an optional `preview` parameter to the quote endpoints. A new pattern for clients who integrate with multiple providers might be:
* Get preview quotes from all providers
* Let the user select a provider based off the preview quotes
* Once the provider …

feat(quotes): Add ability to preview quotes

---

swagger.yaml

Two small things in this PR:
1. The field names in account data weren't matching the spec; this updates them to match e.g. [here](https://github.com/fiatconnect/specification/blob/main/fiatconnect-api.md#343221-http-200).
2. The syntax used to specify the key type for the `GET /accounts` response (`<FiatAccountTypeEnum>`) was not working correctly during validation, so I've updated the swagger spec to use `additionalProperties` instead and drop this constraint.

fix(swagger): Update account field naming, fix GetFiatAccountsResponse validation

---

fiatconnect-api.md

Previously, the meaning of `fee` was ambiguous because `cryptoAmount` and `fiatAmount` denoted an exchange rate that was singular for the quote, but `fee` could vary per account type if multiple account types are accepted for the same quote.
This PR disambiguates the meaning of `fee` by making it singular as well (one fee per quote). 
As a side effect, providers will not be able to offer different fees per account type for the same quote. However, this was *already the case* because of how `cryptoAmount` and `fiatAmount` are defined, as the exact amount in/out for a transfer (fees and all!). This spec change is designed to avoid a breaking change on the CICO provider side by simply moving an optional field to a different place within the same quote response.
An alternative approach would …

docs(fee): disambiguate fees

---

swagger.yaml

This addes to change in documentation in #78 by moving the `QuoteResponse` fee entries to under `quote` from nested under `fiatAccount`.

docs(fee): update swagger description to match fees

---

fiatconnect-api.md

BREAKING CHANGE: use v1= instead of s= for webhook signatures
This matches the Persona webhook signing scheme better, which is linked to in that section. We (Valora) and at least one other group (Bitssa) have already accidentally implemented webhook request signing and validation this way, probably because the linked-to example uses it.

fix(webhooks)!: use v1= for hmac signatures

---

fiatconnect-api.md
package.json
swagger.yaml

There are only 4 supported operators in the spec, and about 144 in sub-saharan Africa alone. Given that this list may also change over time, I don't think it's wise to try to maintain an enum so large in the FiatConnect spec and all the downstream repos that depend on it (particularly https://github.com/fiatconnect/fiatconnect-types).
I suggest that CICO providers use allowedValues to enumerate the mobile money operators supported by their API. Otherwise, clients are welcome to implement their own drop-downs or auto-complete algorithms for this field to try to proactively sanitize the user inputs and prevent users from getting transfers rejected on account of bad `operator` inputs. (Again, CICO providers are ultimately responsible for advertising the list of mobile money providers that …

refactor(mobile-money): change mobile money operator field to string

---

fiatconnect-api.md
package.json
swagger.yaml

To match https://github.com/fiatconnect/fiatconnect-types/pull/117. These were missing from the enum in the spec, which is likely why they were also missing from the types repo.

fix: Make error and transfer enum values consistent with specification

---

fiatconnect-api.md
swagger.yaml

See #90; this is just a new PR with minor styling/syntax changes applied to expedite the process of getting the content merged. (I tried using `git format-patch` and `git am` but got frustrated and gave up :sweat_smile:)

feat:Adding ability to send back picture of Id document (w/ minor changes)

---

fiatconnect-api.md
package.json
swagger.yaml

Currently, it is difficult, if not impossible, for a client to determine _which_ transaction on the blockchain represents the payment from provider to end-user for a transfer in. While the provider _does_ need to inform the client of the provider-owned address that funds will be sent from, this is not necessarily sufficient to determine the actual transfer that contains the sent funds (and even when it is "sufficient", it can be challenging and error-prone to track down the transaction). 
For example, if a user initiates two "transfer in" transactions _for similar amounts_ in parallel with a provider, and the provider sends funds from the same address for both transfers, it would be extremely difficult to determine which blockchain TX corresponds to which FC transfer.
This PR updates both …

feat(txhash): Add `txHash` to transfer in status responses

---

package.json
swagger.yaml

The user action details enum in the swagger spec differs from the actual specification, and thus the most recent changes to the fiatconnect-types repo. During testing, this was causing validations to fail where they shouldn't.

fix(swagger): Update user action detail enum in swagger spec

---

fiatconnect-api.md
package.json
swagger.yaml

This PR adds in a new `URLUserAction` User Action Details Schema, which has the same schema as the existing `PSEUserAction` schema, but lacks the semantics of being explicitly for the PSE payment system. As a result, the `PSEUserAction` schema is being deprecated; it is still supported by the FiatConnect spec, but its use is discouraged.

feat(user actions): Add URLUserAction schema

---

fiatconnect-api.md
package.json
swagger.yaml

We've seen FiatConnect providers use the URLUserActionDetails schema and direct users to their own website just to explain to them that they need to send funds to the same CICO provider's bank account. This defies the intention of the UserActionDetails feature, which is supposed to give FiatConnect clients a chance to explain to users what steps are needed to complete a transfer in-- not just hand them off to complete arbitrary steps on some other website. This PR adds a UserActionDetails schema that should bridge the gap, allowing CICO providers to solicit a bank transfer from end-users without redirecting them to another website.

feat(user-action-details): add AccountNumberUserAction
